on:
  pull_request:

permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
      actions: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: zizmorcore/zizmor-action@b1d7e1fb5de872772f31590499237e7cce841e8e # v0.5.3

  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        persist-credentials: false
    - uses: asdf-vm/actions/install@b7bcd026f18772e44fe1026d729e1611cc435d47 # v4
      with:
        tool_versions: |
          action-validator 0.9.0
    - run: action-validator --verbose ./action.yml

  test:
    needs:
    - lint
    - check
    runs-on: ubuntu-latest
    permissions:
      contents:  read
    env:
      MC_USER: user
      MC_PASS: minio123
    services:
      minio:
        image: fclairamb/minio-github-actions
        env:
          MINIO_ROOT_USER: user
          MINIO_ROOT_PASSWORD: minio123
        ports:
        - 9001:9000
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        persist-credentials: false
    - uses: ./
    - run: mc alias set minio http://127.0.0.1:9001 $MC_USER $MC_PASS
    - run: mc mb minio/test
    - run: mc cp action.yml minio/test/
    - run: mc ls minio/test

  test-inputs:
    needs:
    - lint
    - check
    runs-on: ubuntu-latest
    permissions:
      contents: read
    services:
      minio:
        image: fclairamb/minio-github-actions
        env:
          MINIO_ROOT_USER: user
          MINIO_ROOT_PASSWORD: minio123
        ports:
        - 9002:9000
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        persist-credentials: false
    - uses: ./
      with:
        alias-name: example
        alias-url: http://127.0.0.1:9002
        alias-access-key: user
        alias-secret-key: minio123
    - run: mc mb example/test-bucket
    - run: mc ls example/test-bucket
